SELECT CAPRODUC.Idproducto idproducto,
       CAPROD.IDCICLO CICLO,
       FAPER.IDPERIODO PERIODO,
       LECONS.CONSUMO CONSUMO_ACTUAL,
       LECONS.CONSUPROME CONSUMO_PROMEDIO,
       LECONS.CONSU1 CONSUMO_MES_1,
       LECONS.CONSU2 CONSUMO_MES_2,
       LECONS.CONSU3 CONSUMO_MES_3,
       LECONS.CONSU4 CONSUMO_MES_4,
       LECONS.CONSU5 CONSUMO_MES_5,
       LECONS.CONSU6 CONSUMO_MES_6,
       LECONS.LECT_ACTUAL LECTURA_ACTUAL,
       LECONS.LECT_ANTERIOR LECTURA_ANTERIOR,
       PKG_MDMEPUNTOMEDI.FVAGETIDEQUIPO(CAPRODUC.IDPUNTOMEDI) EQUIPO,
       PKG_MDLECOBSERVALECTU.FVAGETNOMBRE(LECONS.IDOBSERVACION) OBSERVACION_LECTURA,
       INITCAP(pkg_mdlectipocobro.fVAGetNOMBRE(lecons.idtipocobro)) TIPO,
       PKG_MDCAESTATECNI.FVAGETDESCESTATECNI(CAPROD.IDESTATECNI) ESTADO_TECNICO,
       PKG_MDCARESPOSERVI.FVAGETNOMBRERESPSERV(PKG_MDCACONTRATO.FNUGETIDRESPONSABLE(CAPROD.IDCONTRATO)) || ' ' ||
       PKG_MDCARESPOSERVI.FVAGETSEGUNDONOMBRE(PKG_MDCACONTRATO.FNUGETIDRESPONSABLE(CAPROD.IDCONTRATO)) || ' ' ||
       PKG_MDCARESPOSERVI.FVAGETPRIMERAPELLIDO(PKG_MDCACONTRATO.FNUGETIDRESPONSABLE(CAPROD.IDCONTRATO)) || ' ' ||
       PKG_MDCARESPOSERVI.FVAGETSEGUNDOAPELLIDO(PKG_MDCACONTRATO.FNUGETIDRESPONSABLE(CAPROD.IDCONTRATO)) NOMBRE,
       NVL((SELECT T.DESCDIRECC
             FROM CADIRECCION T
            WHERE T.IDPREDIO =
                  PKG_MDCACONTRATO.FNUGETIDPREDIO(CAPROD.IDCONTRATO)),
           PKG_MDCARESPOSERVI.FVAGETDIRCORRESP(PKG_MDCACONTRATO.FNUGETIDRESPONSABLE(CAPROD.IDCONTRATO))) DIRECCION,
       PKG_MDLECRUTA.FVAGETRUTA(CAPROD.IDRUTA) RUTA,
       CAPROD.IDCONTRATO CONTRATO,
       (SELECT COUNT(1)
          FROM FACUENTA A
         WHERE A.IDPRODUCTO = CAPROD.IDPRODUCTO
           AND SALDOCUENTA > 0) CUENTAS_CON_SALDO,
       PKG_MDCABARRIO.FVAGETDESCBARRIO(CADIRE.IDBARRIO) BARRIO,
       PKG_MDCAUSO.FVAGETDESCUSO(CAPROD.IDUSO) USO,
       CAPROD.IDESTRATO || ' - ' ||
       PKG_MDCAESTRATO.FVAGETDESESTRATO(CAPROD.IDUSO, CAPROD.IDESTRATO) ESTRATO,
       CAPROD.IDZONAOPER ZONA,
       (SELECT MAX(CA.DESCDIRECC)
          FROM CADIRECCION CA
         WHERE CA.IDPREDIO = CAPRED.IDPREDIO) DIREC_PREDIO,
       PKG_MDLECMARCEQUIMEDI.FVAGETNOMBRE(PKG_MDLECEQUIPMEDIC.FNUGETIDMARCA(PKG_MDMEPUNTOMEDI.FVAGETIDEQUIPO(CAPRODUC.IDPUNTOMEDI))) MARCA,
       PKG_MDLECREFERMARCA.FVAGETNOMBRE(PKG_MDLECEQUIPMEDIC.FNUGETIDMARCA(PKG_MDMEPUNTOMEDI.FVAGETIDEQUIPO(CAPRODUC.IDPUNTOMEDI)),
                                        PKG_MDLECEQUIPMEDIC.FNUGETIDREFEMARCA(PKG_MDMEPUNTOMEDI.FVAGETIDEQUIPO(CAPRODUC.IDPUNTOMEDI))) REF_TIPO
       --PKG_MDMEPUNTOMEDI.FDAGETFECHAREGISTRO(CAPRODUC.IDPUNTOMEDI) FECHA_REGISTRO_MEDIDOR
       FAPER.PERIANO anio,
       FAPER.PERIMES mes
  FROM CAPRODUCTOS  CAPROD,
       CADIRECCION  CADIRE,
       CAPRODUCMEDI CAPRODUC,
       FAPERIODO    FAPER,
       CAPREDIO     CAPRED,
       CABARRIO     CABAR,
       LECONSUMOS   LECONS
 WHERE CAPRODUC.ESTADO = 'S'
   AND PKG_MDCACONTRATO.FNUGETIDPREDIO(CAPROD.IDCONTRATO) = CADIRE.IDPREDIO
   AND CAPROD.IDPRODUCTO = CAPRODUC.IDPRODUCTO
   AND CADIRE.IDPREDIO = CAPRED.IDPREDIO
   AND CAPRED.IDBARRIO = CABAR.IDBARRIO
   AND LECONS.IDPERIODO = FAPER.IDFAPERICONSU
   AND LECONS.IDPUNTOMEDI = CAPRODUC.IDPUNTOMEDI
   --AND FAPER.PERIANO = &NUA
   --AND FAPER.PERIMES = &NUB
   --AND FAPER.IDCICLO = DECODE(&NUC, -1, FAPER.IDCICLO, &NUC)
   AND CAPROD.IDSERVICIO = 1;
