CREATE TABLE DATAMINING.LACITY_CRIMES (
	DR_NO NUMBER(15,0) NOT NULL,
	DATE_RPTD VARCHAR2(22) NULL,
	AREA NUMBER(15,0) NULL,
	AREA_NAME VARCHAR2(11) NULL,
	CRM_CD NUMBER(15,0) NULL,
	CRM_CD_DESC VARCHAR2(56) NULL,
	CONSTRAINT LACITY_CRIMES_PK PRIMARY KEY (DR_NO)
);

CREATE TABLE DATAMINING.LACITY_CRIMES_GROUPS (
	DR_NO NUMBER(15,0) NOT NULL,
	DATE_RPTD VARCHAR2(22) NULL,
	VICT_AGE NUMBER(15,0) NULL,
	VICT_SEX VARCHAR2(1) NULL,
	VICT_DESCENT VARCHAR2(1) NULL,
	PREMIS_CD NUMBER(15,0) NULL,
	PREMIS_DESC VARCHAR2(80) NULL,
	WEAPON_USED_CD NUMBER(15,0) NULL,
	WEAPON_DESC VARCHAR2(46) NULL,
	STATUS VARCHAR2(2) NULL,
	STATUS_DESC VARCHAR2(12) NULL,
	CONSTRAINT LACITY_CRIMES_GROUPS_PK PRIMARY KEY (DR_NO)
);
