SELECT DR_NO, DATE_RPTD, AREA, AREA_NAME, CRM_CD, CRM_CD_DESC FROM DATAMINING.LACITY_CRIMES;

SELECT COUNT(1) FROM DATAMINING.LACITY_CRIMES;


SELECT DR_NO, DATE_RPTD, VICT_AGE, VICT_SEX, VICT_DESCENT, PREMIS_CD, PREMIS_DESC, WEAPON_USED_CD, WEAPON_DESC, STATUS, STATUS_DESC FROM DATAMINING.LACITY_CRIMES_GROUPS;

SELECT COUNT(1) FROM DATAMINING.LACITY_CRIMES_GROUPS;